{% set name = "sage" %}
{% set version = "9.2" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 1
  skip: true  # [win]
  skip: true  # [py2k or (py3k and py<36)]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
  run:
    # We require all dependencies with at least that version that upstream uses
    # in their SPKGs. For packages that (seem to) use semantic versioning and
    # are at least 1.0.0, we limit the version to the next major release.
    - alabaster >=0.7.12
    - appnope >=0.1.0                                   # [osx]
    - arb
    - babel >=2.6.0,<3
    - bdw-gc >=8.0.4,<9
    - bleach >=3.1.5,<4
    - brial
    - cddlib >=1!0.94j
    - certifi
    - cliquer
    - cvxopt >=1.2.5,<2
    - cycler >=0.10.0
    - cypari2
    - cysignals
    - cython >=0.29.21
    - decorator >=4.4.0,<5
    - docutils >=0.14
    - ecl >=20.4.24,<20.5.0.a0
    - eclib
    - ecm
    - entrypoints >=0.3
    - fflas-ffpack >=2.4.3
    - flintqs >=1.0,<2
    - fplll >=5.3.3,<6
    - fpylll >=0.5.1dev
    - freetype >=2.10.1,<3
    - gap-defaults >=4.10.2
    - gf2x >=1.3,<2
    - gfan >=0.6.2
    - giac >=1.5.0.87,<2
    - givaro >=4.1.1,<5
    - glpk
    - gmp
    - gmpy2
    - gsl
    - iml
    - ipykernel >=5.2.1,<6
    - ipython >=7.13.0,<8
    - ipython_genutils >=0.2.0
    - ipywidgets >=7.5.1,<8
    - jinja2
    - jmol >=14.29.52,<15
    - jsonschema >=3.2.0,<4
    - jupyter_client >=6.1.6,<7
    - jupyter_core
    - lcalc
    - libbraiding
    - libflint
    - libgd
    - libhomfly
    - libiconv >=1.15,<2
    - libpng
    - linbox >=1.6.3
    - lrcalc
    - m4ri
    - m4rie
    - matplotlib-base >=3.3.1,<4
    - maxima >=5.44.0,<6
    - mistune >=0.8.4
    - mpc
    - mpfi
    - mpfr
    - mpmath >=1.1.0,<2
    - nauty >=2.7r1,<3
    - nbconvert >=5.6.1,<7
    - nbformat >=5.0.7,<6
    - ncurses >=6.0,<7
    - networkx >=2.4,<3
    - notebook >=6.1.1,<7
    - ntl
    - numpy
    - palp >=2.11,<3
    - pari >=2.11.4,<3
    # path.py 7 has not been built for Python3 on conda-forge, so we use the latest version
    - path.py >=7.1
    - pexpect >=4.8.0,<5
    - pkg-config
    - pkgconfig
    - pickleshare >=0.7.5,<1.0
    - pillow >=7.2.0,<8
    - planarity
    - ppl
    - pplpy 
    - prompt_toolkit >=3.0.5,<4
    - psutil >=5.2.0,<6
    - ptyprocess >=0.5.1,<1
    - pygments >=2.3.1,<3
    - pynac >=0.7.26,<0.8
    - pyparsing >=2.3.0,<3
    - python
    - python-dateutil >=2.8.1,<3
    - pytz >=2020.1
    - pyzmq >=19.0.2,<20
    - ratpoints
    - readline
    - rpy2 >=3.3.5,<4
    - rubiks >=20070912
    - rw
    - sagelib {{ version }}
    - sagemath-db-combinatorial-designs >=20140630
    - sagemath-db-conway-polynomials >=0.5
    - sagemath-db-elliptic-curves >=0.8.1
    - sagemath-db-graphs >=20161026
    - sagemath-db-polytopes >=20170220
    - sagetex >=3.5
    - scipy >=1.5.2
    - simplegeneric >=0.8.1,<1
    - singular
    - six >=1.15.0,<2
    - sphinx >=3.1.2,<4
    - sqlite >=3.29,<4
    - symmetrica
    - sympow >=2.023.6,<3
    - sympy >=1.6.2,<2
    - tachyon 0.99.*
    - terminado >=0.8.3
    - three.js 117
    - tornado >=6.0.4,<7
    - traitlets >=4.3.2,<6
    - wcwidth >=0.1.7,<2
    - widgetsnbextension >=3.5.1,<4
    - zeromq >=4.2.5,<5
    - zlib
    - zn_poly

    #- sagenb_export
    # required for sage.misc.package.pip_installed_packages
    - pip

    # dev
    #- gcc
    #- git

    # build-time dependencies
    #- vcversioner
    #- setuptools_scm
    #- boost-cpp
    #- pkgconfig

test:
  requires:
    - bc
    - git
  commands:
    - sage -v
    - sage -c 1+1
    - echo exit | sage

about:
  home: http://sagemath.org
  license: GPL-2.0-or-later
  summary: 'Sage - Open Source Mathematical Software'
  description: |
    Creating a Viable Open Source Alternative to Magma, Maple, Mathematica, and MATLAB.
  doc_url: https://doc.sagemath.org/
  dev_url: https://trac.sagemath.org

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
