{% set name = "sage" %}
{% set version = "9.5" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 0
  noarch: generic

requirements:
  run:
    # We require all dependencies with at least that version that upstream uses
    # in their SPKGs. For packages that (seem to) use semantic versioning and
    # are at least 1.0.0, we limit the version to the next major release.
    - alabaster >=0.7.12
    - arb
    - babel >=2.6.0,<3
    - bdw-gc >=8.0.4,<9
    - blas-devel
    - bleach >=3.1.5,<4
    - brial
    - cddlib >=1!0.94m
    - certifi
    - cliquer
    - cvxopt >=1.2.7,<2
    - cycler >=0.11.0
    - cypari2
    - cysignals
    - cython >=0.29.24
    - decorator >=4.4.2,<5
    - docutils >=0.17.1
    - ecl >=21.2.1,<21.2.2.a0
    - eclib
    - ecm
    - entrypoints >=0.3
    - fflas-ffpack >=2.4.3
    - flintqs >=1.0,<2
    - fplll >=5.4.1,<6
    - fpylll >=0.5.6
    - freetype >=2.10.4,<3
    - gap-defaults >=4.11.1
    - gf2x >=1.3,<2
    - gfan >=0.6.2
    - giac >=1.6.0.47,<2
    - givaro >=4.1.1,<5
    - glpk
    - gmp
    - gmpy2
    - gsl
    - iml
    - ipykernel >=6.6.0,<7
    - ipython >=7.29,<8
    - ipython_genutils >=0.2.0
    - ipywidgets >=7.6.5,<8
    - jinja2
    - jmol >=14.29.52,<15
    - jsonschema >=3.2.0,<4
    - jupyter_client >=7.1.0,<8
    - jupyter_core
    - lcalc
    - libbraiding
    - libflint
    - libgd
    - libhomfly
    - libiconv >=1.15,<2
    - libpng
    - linbox >=1.6.3
    - lrcalc
    - m4ri
    - m4rie
    - matplotlib-base >=3.5.1,<4
    - maxima >=5.45.0,<6
    - mistune >=0.8.4
    - mpc
    - mpfi
    - mpfr
    - mpmath >=1.2.1,<2
    - nauty >=2.7r1,<3
    - nbclient >=0.5.9,<0.6
    - nbconvert >=6.1.0,<7
    - nbformat >=5.1.3,<6
    - ncurses >=6.0,<7
    - networkx >=2.6.3,<3
    - notebook >=6.4.6,<7
    - ntl
    - numpy
    - palp >=2.11,<3
    - pari >=2.13.3,<3
    - pexpect >=4.8.0,<5
    - pkg-config
    - pkgconfig
    - pickleshare >=0.7.5,<1.0
    - pillow >=8.4.0,<9
    - planarity
    - ppl
    - pplpy 
    - prompt_toolkit >=3.0.22,<4
    - psutil >=5.2.0,<6
    - ptyprocess >=0.5.1,<1
    - pygments >=2.10.0,<3
    - pynac >=0.7.29,<0.8
    - pyparsing >=3.0.6,<4
    - python >=3.7
    - python-dateutil >=2.8.2,<3
    - pythran >=0.10.0,<0.11
    - pytz >=2021.3
    - pyzmq >=22.0.3
    - ratpoints
    - readline
    - rpy2 >=3.3.6,<4
    - rubiks >=20070912
    - rw
    - sagelib {{ version }}
    - sagemath-db-combinatorial-designs >=20140630
    - sagemath-db-conway-polynomials >=0.5
    - sagemath-db-elliptic-curves >=0.8.1
    - sagemath-db-graphs >=20210214
    - sagemath-db-polytopes >=20170220
    - sagetex >=3.5
    - scipy >=1.6.3
    - simplegeneric >=0.8.1,<1
    - singular
    - six >=1.15.0,<2
    - sphinx >=4.0.1,<5
    - sqlite >=3.29,<4
    - symmetrica
    - sympow >=2.023.6,<3
    - sympy >=1.8,<2
    - tachyon 0.99.*
    - terminado >=0.8.3
    - three.js 122
    - tornado >=6.0.4,<7
    - traitlets >=4.3.3,<6
    - wcwidth >=0.1.7,<2
    - widgetsnbextension >=3.5.1,<4
    - zeromq >=4.2.5,<5
    - zlib
    - zn_poly

    #- sagenb_export
    # required for sage.misc.package.pip_installed_packages
    - pip

    # dev
    #- gcc
    #- git

    # build-time dependencies
    #- vcversioner
    #- setuptools_scm
    #- boost-cpp
    #- pkgconfig

test:
  requires:
    - bc
    - git
    - patch
  commands:
    - sage -v
    - sage -c 1+1
    - echo exit | sage

about:
  home: http://sagemath.org
  license: GPL-2.0-or-later
  license_file: COPYING.txt
  summary: 'Sage - Open Source Mathematical Software'
  description: |
    Creating a Viable Open Source Alternative to Magma, Maple, Mathematica, and MATLAB.
  doc_url: https://doc.sagemath.org/
  dev_url: https://trac.sagemath.org

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
