travis:
  secure:
    BINSTAR_TOKEN: juIn2dFWgkhVvJh5DeJnWpS2+UYksJ4AErV/i6w9e8buJgB5Ig1Vf3J6FBHuSL3b4CmLmfXJD+D4Flb7ploaqAna8NQr1mzI515Lnm8mwi1E/g03GFnd1GJvhWlPhsE9gAMPVelaIWmJRqBh0ucu5S7EKikyey9mbzvvNmt7nIWmSQk9nJTgaXYMYPnTQeLWVjjKY5tiy4yAGztGB5pp09SzRboCBWvVUxd6bZGmB4fjZvfGMbIJ9f+wamL1aBVT9UEtj1B0nKiYQkAmBF7+arqLkmokVcXxA9d6wFBgmase9YV2E9g8UfHjCONOVIlou19L6ZLTlVpla8QV98VZhPjOQZmJY9XFgjPsg5OV0IAoH1TLs9FWNi4e6TyPPcxrLo3MvmFqcZyR67AEQy84G58NL3GaWdyhk4w5hTCxB+ZzRDUszHQH02gW2xib1g47q6tOZ15s9cU5MzSBrvBkq9Jx8PYpWsDqvKyls1nlHuGtD6uK2BSWu6UxokhQJLBCDc73CpzpQuy478h8xIjwh+Idbf2i9tH2PZTnyV8HdO7C0uPPVjfDNb6aPL9nGmGlMeRp8NUpfhDLhwXcU+RsdDbgRJfAluKc/oT9O07YvtIzGS6sMd9iQGVmL7Fh5ZtlrFY1Aa0LbiWDokO4nHQbVeybOc7efcTxWaIqnM3thUw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
