travis:
  secure:
    BINSTAR_TOKEN: BNMs3AGMatrgXtoDZZTPgd1M+T4yDEe+BEPw2oFD99/M5+Jnz/4Hm55B+sHI1oVaw784s34i2QoPyRuCe4AusYS/3D/mPVxCWxiwsH+lhH3+8xdQh1L9KOvHRDNmPk4+Ac1ey5P2t6DNCBPO2fEhBt0yKhg33Rxz5FFgJrSltNyRs5s3AH3E2rUwQJLWU5mLpS416xrlDKm87YXJD1dSq5K/TyMN0rMm4PoBMenkRT58aclKerVGPUiLYZfOj6VfDgulu+PvTTzmfnNOzTZpjZ7Vj+52heCpq+t3a8Ys3XNp91R93sW4TGQ+eqi/Vhrki8cfhocdlPCDvVc+xm1VkCp3QZ/doa9pUtY0YgnevBc+MO599M5WK79W6l7Z5Oh+LuCWh2Z3vs/smmlho0Urk98EKPUfdTcwowGZrs/ApXWXoeYszwX48ZIAl9906UsmUKtZVgE/2VVntTYkmgTEe2a8CuUL+7O41wiYOtz1VeBGMGJ0HXs2SuupD0XCKKViTe6EV385K1NDAWxnahKbt0Wub8AYO54QAFXGxNUZE7zKroTOXDK9CJ80JEhiqhlSzsWXqolEqGwQHuGjADdFPP6GCnPTl6rqKwWXXE0L3u3m31/ij6OLRLXm3NInhS+AIwQW0cE42WUMCxtJpv1ya/oYcz0B7Gfm/PsY6cg4Xj4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
