travis:
  secure:
    BINSTAR_TOKEN: Zv/mD24qmggEGuUQlQHo9FNrfBMphPrZvRQXsG/bhRLoGFvDCR5sthsvrKlWZp+sBO9JhnBMdd1xkSV5ufsDYi1XQrPPbZv72StNAet6EYv2cDvDj1q+EQ9i1C9hmPKaDXaOn8sEwAlqCI964dmzFeWYGorTtn2MPalhASlxMZisy1FFcWXUoyP0WEG3FOJ4o0ENFombr2kX6B7lp+IaQhy4IHuEHLT9NyWVZPw6pT7ph+mxRWnGQUnRm2kSb+ZXsCprDasMDVrhrE41BCCDZA5ggqQUMVL5MzzXOQ8s0MmqeCAoHZh9PnSuaBaooeMbhFa8IbVbTnPGUdUQyH/szwxQyrrQj3CFNTPz2ZqLajdMQBTc+bQU4a/U3HnLpxiFaAxzV4FJFyTP133dDBbo+tvNZ+9mR4DlL9WD9Y00Nhx/35+oX82lHxmKWiw3lDGdnFf3JuadORQjH2P+3aYoBGEA7hEv0zlS+ZLpH5L/3+7xi8FJwYTYLfNQHyMSP/YxLIzrGnqfXuVv0WzklPQI81OFdUHT6xEtXQ9bhtsM5ysSEnn+IlbCA+LDsPlk9t1CmJ+q99Q2pVaeWfKc+HpTnV1/BVDcL2c9QPEK4XzYYyWB6PN0ZiNmNKq+oAHEiPWXNnwTRlm5ObKz2YI4gz8aTUYGkaRd0x6IqLZrn8tyaio=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
