# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: osx
  pool:
    vmImage: macOS-10.13
  timeoutInMinutes: 360
  strategy:
    maxParallel: 8
    matrix:
      osx_python2.7:
        CONFIG: osx_python2.7
        UPLOAD_PACKAGES: True
      osx_python3.6:
        CONFIG: osx_python3.6
        UPLOAD_PACKAGES: True
      osx_python3.7:
        CONFIG: osx_python3.7
        UPLOAD_PACKAGES: True

  steps:
  # TODO: Fast finish on azure pipelines?
  - script: |
      echo "Fast Finish"
      

  - script: |
      echo "Removing homebrew from Azure to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew
    displayName: Remove homebrew

  - bash: |
      echo "##vso[task.prependpath]$CONDA/bin"
      sudo chown -R $USER $CONDA
    displayName: Add conda to PATH

  - script: |
      source activate base
      conda install -n base -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
    displayName: 'Add conda-forge-ci-setup=2'

  - script: |
      source activate base
      echo "Configuring conda."

      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml
      export CI=azure
      source run_conda_forge_build_setup
      conda update --yes --quiet --override-channels -c conda-forge -c defaults --all
    env: {
      OSX_FORCE_SDK_DOWNLOAD: "1"
    }
    displayName: Configure conda and conda-build

  - script: |
      source activate base
      conda create --yes -n sage python=2 sagelib=8.9.rc0
      source activate sage
      conda install --yes python=2 sagelib=8.9.rc0 'alabaster>=0.7.12'
      conda install --yes python=2 sagelib=8.9.rc0 'appnope>=0.1.0'
      conda install --yes python=2 sagelib=8.9.rc0 'arb'
      conda install --yes python=2 sagelib=8.9.rc0 'babel>=2.6.0,<3'
      conda install --yes python=2 sagelib=8.9.rc0 'backports.functools_lru_cache>=1.5,<2'
      conda install --yes python=2 sagelib=8.9.rc0 'backports.shutil_get_terminal_size>=1.0.0,<2'
      conda install --yes python=2 sagelib=8.9.rc0 'backports_abc>=0.5'
      conda install --yes python=2 sagelib=8.9.rc0 'bdw-gc>=7.6.4,<9'
      conda install --yes python=2 sagelib=8.9.rc0 'bleach>=3.0.2,<4'
      conda install --yes python=2 sagelib=8.9.rc0 'brial'
      conda install --yes python=2 sagelib=8.9.rc0 'cddlib>=1!0.94j'
      conda install --yes python=2 sagelib=8.9.rc0 'certifi>=2019.3.9'
      conda install --yes python=2 sagelib=8.9.rc0 'cliquer'
      conda install --yes python=2 sagelib=8.9.rc0 'configparser>=3.7.3,<4'
      conda install --yes python=2 sagelib=8.9.rc0 'cvxopt>=1.1.8,<2'
      conda install --yes python=2 sagelib=8.9.rc0 'cycler>=0.10.0'
      conda install --yes python=2 sagelib=8.9.rc0 'cypari2'
      conda install --yes python=2 sagelib=8.9.rc0 'cysignals'
      conda install --yes python=2 sagelib=8.9.rc0 'cython>=0.29.12'
      conda install --yes python=2 sagelib=8.9.rc0 'decorator>=4.4.0,<5'
      conda install --yes python=2 sagelib=8.9.rc0 'docutils>=0.14'
      conda install --yes python=2 sagelib=8.9.rc0 'ecl>=16.1.2,<16.1.3'
      conda install --yes python=2 sagelib=8.9.rc0 'eclib'
      conda install --yes python=2 sagelib=8.9.rc0 'ecm'
      conda install --yes python=2 sagelib=8.9.rc0 'entrypoints>=0.3'
      conda install --yes python=2 sagelib=8.9.rc0 'fflas-ffpack>=2.4.3'
      conda install --yes python=2 sagelib=8.9.rc0 'flintqs>=1.0,<2'
      conda install --yes python=2 sagelib=8.9.rc0 'fplll>=5.2.1,<6'
      conda install --yes python=2 sagelib=8.9.rc0 'fpylll>=0.4.1dev'
      conda install --yes python=2 sagelib=8.9.rc0 'freetype>=2.9.1,<3'
      conda install --yes python=2 sagelib=8.9.rc0 'functools32>=3.2.3,<4'
      conda install --yes python=2 sagelib=8.9.rc0 'future>=0.17.1'
      conda install --yes python=2 sagelib=8.9.rc0 'gap-defaults>=4.10.2'
      conda install --yes python=2 sagelib=8.9.rc0 'gf2x>=1.2,<2'
      conda install --yes python=2 sagelib=8.9.rc0 'gfan>=0.6.2'
      conda install --yes python=2 sagelib=8.9.rc0 'giac>=1.5.0.63,<2'
      conda install --yes python=2 sagelib=8.9.rc0 'givaro>=4.1.1,<5'
      conda install --yes python=2 sagelib=8.9.rc0 'glpk'
      conda install --yes python=2 sagelib=8.9.rc0 'gmp'
      conda install --yes python=2 sagelib=8.9.rc0 'gmpy2'
      conda install --yes python=2 sagelib=8.9.rc0 'gsl'
      conda install --yes python=2 sagelib=8.9.rc0 'iml'
      conda install --yes python=2 sagelib=8.9.rc0 'ipykernel>=4.8.2,<5'
      conda install --yes python=2 sagelib=8.9.rc0 'ipython>=5.8.0,<6'
      conda install --yes python=2 sagelib=8.9.rc0 'ipython_genutils>=0.2.0'
      conda install --yes python=2 sagelib=8.9.rc0 'ipywidgets>=7.4.2,<8'
      conda install --yes python=2 sagelib=8.9.rc0 'jinja2'
      conda install --yes python=2 sagelib=8.9.rc0 'jmol>=14.6.1,<15'
      conda install --yes python=2 sagelib=8.9.rc0 'jsonschema>=2.6.0,<3'
      conda install --yes python=2 sagelib=8.9.rc0 'jupyter_client>=5.2.4,<6'
      conda install --yes python=2 sagelib=8.9.rc0 'jupyter_core'
      conda install --yes python=2 sagelib=8.9.rc0 'lcalc'
      conda install --yes python=2 sagelib=8.9.rc0 'libbraiding'
      conda install --yes python=2 sagelib=8.9.rc0 'libflint'
      conda install --yes python=2 sagelib=8.9.rc0 'libgd'
      conda install --yes python=2 sagelib=8.9.rc0 'libhomfly'
      conda install --yes python=2 sagelib=8.9.rc0 'libiconv>=1.15,<2'
      conda install --yes python=2 sagelib=8.9.rc0 'libpng'
      conda install --yes python=2 sagelib=8.9.rc0 'linbox>=1.6.3'
      conda install --yes python=2 sagelib=8.9.rc0 'lrcalc'
      conda install --yes python=2 sagelib=8.9.rc0 'm4ri'
      conda install --yes python=2 sagelib=8.9.rc0 'm4rie'
      conda install --yes python=2 sagelib=8.9.rc0 'matplotlib-base>=2.2.4,<3'
      conda install --yes python=2 sagelib=8.9.rc0 'maxima>=5.42.2,<6'
      conda install --yes python=2 sagelib=8.9.rc0 'mistune>=0.8.4'
      conda install --yes python=2 sagelib=8.9.rc0 'mpc'
      conda install --yes python=2 sagelib=8.9.rc0 'mpfi'
      conda install --yes python=2 sagelib=8.9.rc0 'mpfr'
      conda install --yes python=2 sagelib=8.9.rc0 'mpmath>=1.1.0,<2'
      conda install --yes python=2 sagelib=8.9.rc0 'nauty>=2.6r7,<3'
      conda install --yes python=2 sagelib=8.9.rc0 'nbconvert>=5.4.0,<6'
      conda install --yes python=2 sagelib=8.9.rc0 'nbformat>=4.4.0,<5'
      conda install --yes python=2 sagelib=8.9.rc0 'ncurses>=6.0,<7'
      conda install --yes python=2 sagelib=8.9.rc0 'networkx>=2.2,<3'
      conda install --yes python=2 sagelib=8.9.rc0 'notebook>=5.7.6,<6'
      conda install --yes python=2 sagelib=8.9.rc0 'ntl'
      conda install --yes python=2 sagelib=8.9.rc0 'numpy'
      conda install --yes python=2 sagelib=8.9.rc0 'palp>=2.1,<3'
      conda install --yes python=2 sagelib=8.9.rc0 'pari'
      conda install --yes python=2 sagelib=8.9.rc0 'path.py>=7'
      conda install --yes python=2 sagelib=8.9.rc0 'pathlib2>=2.3.3,<3'
      conda install --yes python=2 sagelib=8.9.rc0 'pexpect>=4.6.0,<5'
      conda install --yes python=2 sagelib=8.9.rc0 'pickleshare>=0.7.5'
      conda install --yes python=2 sagelib=8.9.rc0 'pillow>=5.3.0,<6'
      conda install --yes python=2 sagelib=8.9.rc0 'planarity'
      conda install --yes python=2 sagelib=8.9.rc0 'ppl'
      conda install --yes python=2 sagelib=8.9.rc0 'pplpy'
      conda install --yes python=2 sagelib=8.9.rc0 'prompt_toolkit>=1.0.15,<2'
      conda install --yes python=2 sagelib=8.9.rc0 'psutil>=5.2.0,<6'
      conda install --yes python=2 sagelib=8.9.rc0 'ptyprocess>=0.5.1'
      conda install --yes python=2 sagelib=8.9.rc0 'pygments>=2.3.1,<3'
      conda install --yes python=2 sagelib=8.9.rc0 'pynac>=0.7.26,<0.8'
      conda install --yes python=2 sagelib=8.9.rc0 'pyparsing>=2.3.0,<3'
      conda install --yes python=2 sagelib=8.9.rc0 'python'
      conda install --yes python=2 sagelib=8.9.rc0 'python-dateutil>=2.5.3,<3'
      conda install --yes python=2 sagelib=8.9.rc0 'pytz>=2018.7'
      conda install --yes python=2 sagelib=8.9.rc0 'pyzmq>=18.1.0,<19'
      conda install --yes python=2 sagelib=8.9.rc0 'ratpoints'
      conda install --yes python=2 sagelib=8.9.rc0 'readline'
      conda install --yes python=2 sagelib=8.9.rc0 'rpy2>=2.8.2,<3'
      conda install --yes python=2 sagelib=8.9.rc0 'rubiks>=20070912'
      conda install --yes python=2 sagelib=8.9.rc0 'rwsagemath-db-combinatorial-designs>=20140630'
      conda install --yes python=2 sagelib=8.9.rc0 'sagemath-db-conway-polynomials>=0.5'
      conda install --yes python=2 sagelib=8.9.rc0 'sagemath-db-elliptic-curves>=0.8'
      conda install --yes python=2 sagelib=8.9.rc0 'sagemath-db-graphs>=20161026'
      conda install --yes python=2 sagelib=8.9.rc0 'sagemath-db-polytopes>=20170220'
      conda install --yes python=2 sagelib=8.9.rc0 'sagenb>=1.1.2,<1.2'
      conda install --yes python=2 sagelib=8.9.rc0 'sagetex>=3.3'
      conda install --yes python=2 sagelib=8.9.rc0 'scipy>=1.2.0'
      conda install --yes python=2 sagelib=8.9.rc0 'simplegeneric>=0.8.1'
      conda install --yes python=2 sagelib=8.9.rc0 'singledispatch>=3.4.0.3,<4'
      conda install --yes python=2 sagelib=8.9.rc0 'singular'
      conda install --yes python=2 sagelib=8.9.rc0 'six>=1.12.0,<2'
      conda install --yes python=2 sagelib=8.9.rc0 'sphinx>=1.8.5,<2'
      conda install --yes python=2 sagelib=8.9.rc0 'sqlite>=3.22,<4'
      conda install --yes python=2 sagelib=8.9.rc0 'ssl_match_hostname>=3.5.0.1,<4'
      conda install --yes python=2 sagelib=8.9.rc0 'symmetrica'
      conda install --yes python=2 sagelib=8.9.rc0 'sympow>=1.018.1,<2'
      conda install --yes python=2 sagelib=8.9.rc0 'sympy>=1.4,<2'
      conda install --yes python=2 sagelib=8.9.rc0 'tachyon=0.99.*'
      conda install --yes python=2 sagelib=8.9.rc0 'terminado>=0.8.1'
      conda install --yes python=2 sagelib=8.9.rc0 'three.js=105'
      conda install --yes python=2 sagelib=8.9.rc0 'tornado>=4.5.2,<5'
      conda install --yes python=2 sagelib=8.9.rc0 'traitlets>=4.3.2,<5'
      conda install --yes python=2 sagelib=8.9.rc0 'twisted>=18.4.0,<19'
      conda install --yes python=2 sagelib=8.9.rc0 'wcwidth>=0.1.7'
      conda install --yes python=2 sagelib=8.9.rc0 'widgetsnbextension>=3.4.2,<4'
      conda install --yes python=2 sagelib=8.9.rc0 'zeromq>=4.2.5,<5'
      conda install --yes python=2 sagelib=8.9.rc0 'zlib'
      conda install --yes python=2 sagelib=8.9.rc0 'zn_poly'
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml
    displayName: Mangle compiler

  - script: |
      source activate base
      make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
    displayName: Generate build number clobber file

  - script: |
      source activate base
      conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
    displayName: Build recipe

  - script: |
      source activate base
      export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
      upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
    displayName: Upload recipe
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
    condition: not(eq(variables['UPLOAD_PACKAGES'], 'False'))
